"""create expense tables

Revision ID: 2d11b8767f7a
Revises: 
Create Date: 2026-09-23 08:23:11.095337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d11b8767f7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('expense_items',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('expense_name', sa.String(length=100), nullable=False),
    sa.Column('expense_description', sa.String(length=500), nullable=True),
    sa.Column('expense_status', sa.String(length=10), server_default='draft', nullable=False),
    sa.Column('expense_image_url', sa.String(length=500), nullable=True),
    sa.Column('expense_video_url', sa.String(length=500), nullable=True),
    sa.Column('expense_behavior', sa.String(length=16), nullable=True),
    sa.Column('expense_code', sa.Integer(), nullable=True),
    sa.Column('expense_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expense_creator_id', sa.Integer(), nullable=False),
    sa.Column('expense_formed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("expense_behavior IS NULL OR expense_behavior IN ('fixed', 'variable')", name='ck_expense_items_behavior'),
    sa.CheckConstraint("expense_status IN ('draft', 'published', 'deleted')", name='ck_expense_items_status'),
    sa.CheckConstraint('expense_code IS NULL OR expense_code >= 0', name='ck_expense_items_code_nonnegative'),
    sa.ForeignKeyConstraint(['expense_creator_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_index('ix_expense_items_code', 'expense_items', ['expense_code'], unique=False)
    op.create_index('ix_expense_items_status', 'expense_items', ['expense_status'], unique=False)
    op.create_index('uq_expense_items_one_draft_per_creator', 'expense_items', ['expense_creator_id'], unique=True, postgresql_where=sa.text("expense_status = 'draft'"))
    op.create_table('expense_likes',
    sa.Column('expense_like_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense_items.expense_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('expense_like_id'),
    sa.UniqueConstraint('user_id', 'expense_id', name='uq_expense_likes_user_expense')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_likes')
    op.drop_index('uq_expense_items_one_draft_per_creator', table_name='expense_items', postgresql_where=sa.text("expense_status = 'draft'"))
    op.drop_index('ix_expense_items_status', table_name='expense_items')
    op.drop_index('ix_expense_items_code', table_name='expense_items')
    op.drop_table('expense_items')
    op.drop_table('users')
    # ### end Alembic commands ###
